language: java
jdk:
  - oraclejdk8
  - oraclejdk11

script:
  mvn verify

env:
  global:
   # travis encrypt -r subchen/spring-boot-parent MAVEN_DEPLOY_SECRET_PASSWD=......
   - secure: "lq4Yxu5Uck877KV1J4r8f5M8e4JGxKngxatw9ryfQjJVsnasek/kDV73tHhr3iBzW7Y6W1k3/mmTb88ygxrgAq3DVP0xiovB+CS5qhY0ouphYXA/64EqxZQv8ETue0Pfrn5bb6t7+TQIMA7khnttEA4pGeka0F26e6gtzg889alN/CS/8dWzJ/4cu/JjMWcc+mvAT4tV5aOEu5wo7+9FauZcE/Ne3tarxvn4f5ywBvQm40rYKE+IY6HlmnEc1lWGRO4k+DOtVTyXCqYa+LFovJXZPW7W/8RQALcZzvldemJM8BFwRBluOFfDqx40D+t/gOHqhee+CHfz4IJBRmjSuBNlittmz08gDkS7jgIFvv67xx4tmHtpitUmcJeUIb7XvHaLLpASa3QKrLlUglXXTDTDn+G7xyAgZH1DB5ysOkURMNf6Ub3hxovFp1Moygm9iPZFODzKeXaLQmuO5xlBGucwKq68JndoIvHe5i0HQ/bVXAAnNpFjUj2EU5BHYNjs3UMsphAl7FA8KmHC+2Qk0EeiIn/RBsyU2lOX3BMfCDE1DIurx8x3oYadZ4Y3e8L6P+cL1/AWwS8aVTYNa0RZR4kKKsdwbAivFtm9emqjFJ+vZSmE5P2eBhogyPPtNlOPQ0xRdAhzE4B1T7UVJpgTGfSMDQIwXM4YqyiYjUKCXcw="

before_deploy:
  - curl -fSL https://dl.bintray.com/subchen/download/maven/subchen-maven-deploy.tar.gz.enc -O
  - openssl aes-256-cbc -k "$MAVEN_DEPLOY_SECRET_PASSWD" -in subchen-maven-deploy.tar.gz.enc -out subchen-maven-deploy.tar.gz -d
  - tar -zxvf subchen-maven-deploy.tar.gz -C ~/

deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
