language: java
jdk:
  - oraclejdk8
  - oraclejdk11

script:
  mvn verify

env:
  global:
   # travis encrypt -r subchen/spring-boot-parent MAVEN_DEPLOY_SECRET_PASSWD=......
   - secure: "Eh9Z0+QgHg1uCFjJfkulU3tOZ2sBloGr9NXBKcf1WNRh+LVpm4Z7zENkVuLliAMhM43zCAPFzwuSGKbnp/VQNxYNhiBfd0Ei0O7mG9mAuY8CdgGpitn81aw/lM1c2x0vdqDXTqB8n6ntcq4pbfTGF8B4r2yTQnJaQvS+g+CUKURb3NiSMGM4gw3OioyQsGtTXazy7q9bwBxNTbxmKg5NAz3tiZP58dS9PYlaq+KG0tdIMmTFlaZsX8BSzqsSO1wnHPzBDMZUS3Xp0iD5TWIYqlyHNG9OU87yYHKhwQAlU4X6L4kh6d1O181JDZB4y45iXs0oIPZiaXUWs3bnFRwPF51/Pb0npNZwO7efjlWorcxfqeBmGxkNwS/muBnPEd9C9gS03xSi0U2cibwCiDTiK9mL7yf2hBmuLtIy7YBY94n2W06uhmRpk3ryPUD+w8ulgRBZjj5WXzn/UdOTQpCJfKM9o1UHNLraurKJrMHtxAYhq2d4xn/3x7XngE1LR6c0e+hUg4mj7aiqsjG/40KUjHDEhzLaBrHHHAoBVY4nd1X87MkUTp9pd/4memKZZ+4G2ShamsEYaf3C5vonGVJuvJWbTld6WC4t7xArDRdiuvh9Dd/OuAP2Xvcye4QkVJxGKltOsoabY8uhbuaJ7vrvUphauUZWpNQNGfZDeb1dLfg="

before_deploy:
  - curl -fSL https://dl.bintray.com/subchen/download/maven/subchen-maven-deploy.tar.gz.enc -O
  - openssl aes-256-cbc -k "$MAVEN_DEPLOY_SECRET_PASSWD" -in subchen-maven-deploy.tar.gz.enc -out subchen-maven-deploy.tar.gz -d
  - tar -zxvf subchen-maven-deploy.tar.gz -C ~/

deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
